# Generated by Django 3.2.2 on 2021-06-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userverification',
            name='uname',
            field=models.TextField(default=None, max_length=50),
        ),
    ]
